swarmcom/reach-ui

TODO.md
show Stefan how use pull request
=> Change TODO list

src/Agent.vue, src/Agent/AgentState.vue, src/Agent/Dialer.vue, src/Agent/Inqueue.vue, src/Agent/Outgoing.vue, src/Agent/Release.vue, src/custom.scss
- add agent state component
- make similar to old UI
- still in progress, need add/create icons for diferent agent states
=> Agent page change UI

src/Admin/Agent/Groups.vue, src/Admin/Agents.vue, src/Admin/Clients.vue, src/Admin/LineIns.vue, src/Admin/LineOuts.vue, src/Admin/Queue/Groups.vue, src/Admin/Queues.vue, src/Admin/Releases.vue, src/Agent/AgentState.vue, src/Agent/Inqueue.vue, src/Monitor/Agents.vue, src/Widget/Btable.vue
use btable in agent inqueue component, 
add time converter msToHms
rotate icon for ringing agent state
=> Add new options to btable component

src/Agent/AgentState.vue, src/agent.js, src/custom.scss
- Show release drop down in release state was done in https://github.com/swarmcom/reach-ui/commit/54fc0b7072ae985a91cc853724338b5ae3ae05ee 
- Click on release button do release action with last selected release reason
- Show notify message in case last selected release reason is not defined
- Click on release reason drop down do release action with selected release reason  
- Customize agent state button to fit same width as release drop down
=> Allow Agent to change their release mode while already in release state

src/Agent.vue, src/Agent/AgentState.vue, src/Agent/Info.vue, src/Agent/Widget/Release.vue, src/App.vue, src/Login.vue, src/Monitor/Agents.vue, src/Monitor/Inqueues.vue, src/Widget/ToggleBar.vue, src/agent.js, src/custom.scss
- initila work for display sip uri under activity timer. Show my Phone uri  text box with ability to select new uri.
- make button to go release/idle smaller, make drop down box smaller and line up with button.
- show session manager section with smaller font size
- UI remember previous things
=> Display the sip URI under the current activity counter

src/Admin.vue, src/Admin/Agent.vue, src/Admin/Agent/Group.vue, src/Admin/Agent/Persistent.vue, src/Agent.vue, src/Agent/Inqueue.vue, src/Agent/Inqueue/Call.vue, src/Monitor/Agents.vue, src/agent.js, src/custom.scss, src/main.js, src/ws-proto.js
- added changes to make session manager widget similar to old UI
- cherry pick commits from jahmed-devel
=> Martin session manager

src/Monitor/Agents.vue, src/Monitor/Inqueues.vue, src/Monitor/Widget/AgentMonitor.vue, src/Monitor/Widget/AgentProfiles.vue, src/Monitor/Widget/InqueuesMonitor.vue, src/Monitor/Widget/InqueuesView.vue
Add queue manager to look similar as in old UI
I will do optimalization later
=> Martin devel

package.json, src/Admin/Agent.vue, src/Admin/Agent/Group.vue, src/Admin/LineIn.vue, src/Admin/Queue.vue, src/Admin/Queue/Group.vue, src/App.vue, src/Recordings/Player.vue, src/Recordings/Recordings.vue, src/custom.scss, src/main.js, yarn.lock
- implemeted call recording widget in new tab
- allow to search/filter of recordings
- store/load settings from local storage
=> Implement call recording 

src/Recordings/Player.vue, src/Recordings/Recordings.vue
- able to play record from any time
- show time tooltip of record on mouse hover
=> Add seeking options to be able to play record from any time

src/Agent.vue, src/Agent/MyStatistics.vue, src/Agent/SessionManager.vue
- add my statistics component wit hard coded values
- move session manager to own component 
- agent component includes session manager and my statistics component
=> Create My Statistics component 

src/Agent/Info.vue, src/Agent/Skills.vue, src/App.vue, src/Profile.vue, src/Recordings/Player.vue, src/Recordings/Recordings.vue, src/Widget/Agent/Groups.vue, src/Widget/Clients.vue, src/Widget/DispositionGroups.vue, src/Widget/Lines.vue, src/Widget/Luas.vue, src/Widget/MOHs.vue, src/Widget/Prompts.vue, src/Widget/Queue/Groups.vue, src/Widget/Queues.vue, src/Widget/Recipes.vue, src/Widget/ReleaseGroups.vue, src/Widget/Roles.vue, src/main.js
- sync with devel branch
- add popover for search input
- add queue filter
- place call recordings controls under table row, when user click to show it
- add reload recordings functionality
=> Call recordings improvements

src/Agent/CIQ.vue, src/Agent/Count.vue, src/Agent/Inqueue.vue, src/Agent/Inqueue/Conf.vue, src/Agent/Stats.vue, src/Stats/Agent.vue, src/Stats/Agent/Events.vue, src/Stats/Inqueue.vue, src/Stats/Inqueue/Events.vue
=> Sync devel

src/Agent.vue, src/App.vue, src/agent.js, src/custom.scss
- to make it ready for customer demo
=> Allow to add/remove Agent manager/Queue manager from main page 

src/Monitor/Widget/AgentMonitor.vue, src/Monitor/Widget/InqueuesMonitor.vue
- Add search filter to queue manager monitor component
- Use actions for each queue same way as it is in agent manager monitor component
=> Improve agent manager and queue manager monitor

src/Recordings/Records.vue
add skills filter
fix recordings details, client
request recordings with start and end time
=> recordings improvements

src/Agent/Inqueue/Call.vue, src/Agent/MyProfile.vue, src/Monitor/Widget/AgentMonitor.vue, src/agent.js, src/custom.scss
=> Add avatars

package.json, src/Agent/Widget/TransferConference.vue, src/agent.js, yarn.lock
Allow transfer/conference for multiple agents
=> Martin dev

src/Monitor/Widget/AgentMonitor.vue, src/Monitor/Widget/InqueuesMonitor.vue
=> Update the options in the Action drop down of the agent and queue manager

package.json, src/Agent/MyStatistics.vue, src/Login.vue, src/custom.scss
- uses new query to get data
- skills selection
- reach2 look
- fixed start ts of periods for today, this week, this month
=> MyStats widget

src/Monitor/Widget/AgentGroupsStats.vue, src/Monitor/Widget/AgentMonitor.vue
- use of new backend query
- missing data fields
- refresh buttons
=> apply solution for issue #205 (AgentManager Widget)

src/Report/CDR/CDR.vue, src/Report/Empty.vue, src/Report/Input/FromTo.vue, src/Report/Reports.vue, src/Report/Widget/Date.vue, src/Report/reports.scss, src/Role/Supervisor.vue, src/routes/report.js
- CDR report (without outbound calls so far)
=> Initial implementation of Reach2 reports (former Jasper reports) - issue #134

src/Report/Input/Traffic.vue, src/Report/Legacy/Traffic/ClientTrafficOverview.vue, src/Report/Legacy/Traffic/LineTrafficOverview.vue, src/Report/Legacy/Traffic/QueueTrafficOverview.vue, src/Report/reports.scss
- Client Traffic Overview
- Queue Traffic Overview
- Line Traffic Overview
=> add Traffic Overview reports

src/widgets.js
forget to import new component use for real number
=> Import formrealnumber component

src/Admin/Queue/Group.vue
use real number input for aging instead of weight
=> Use real number input for aging in queue group

src/Login.vue, src/Monitor/Agents.vue, src/Monitor/Inqueues.vue, src/Monitor/Widget/AgentGroups.vue, src/Monitor/Widget/AgentGroupsStats.vue, src/Monitor/Widget/AgentMonitor.vue, src/Monitor/Widget/InqueuesMonitor.vue, src/Monitor/Widget/InqueuesView.vue, src/Monitor/Widget/Outgoings.vue, src/Recordings/Player.vue, src/Recordings/Records.vue, src/Storage.vue
- for monitor and recording page
=> formating and storage data 

src/Agent/Inqueue/Call.vue
- show requested skills for queue, queue group, line, client in session manager
- format
=> Show requested skills for queue, queue group, line, client in session manager

src/Monitor/Widget/InqueuesMonitor.vue
- to be similar with agent manager
=> Use table row for actions in queue manager

src/Admin/ACL/Entries.vue, src/Report/Input/EntitySelector.vue, src/Report/Legacy/Agent/AgentAnswerPerformanceByGroup.vue, src/Report/Legacy/Agent/AgentCallDisposition.vue, src/Report/Legacy/Traffic/ClientTrafficDetail.vue, src/Report/Legacy/Traffic/LineTrafficDetail.vue, src/Report/Legacy/Traffic/QueueTrafficDetail.vue
- Agent Call Disposition
- Agent Answer Performance
- new general Entity selector component
=> Agent reports

src/Report/Input/EntitySelector.vue, src/Report/Legacy/Agent/AgentAvailability.vue
+ EntitySelector update, works with both objects and plain strings as
options
=> Agent Availability Report

src/Report/Input/SLA.vue, src/Report/Legacy/Agent/AgentAvailability.vue, src/Report/Legacy/Traffic/ClientTrafficDetail.vue, src/Report/Legacy/Traffic/ClientTrafficOverview.vue, src/Report/Legacy/Traffic/LineTrafficDetail.vue, src/Report/Legacy/Traffic/LineTrafficOverview.vue, src/Report/Legacy/Traffic/QueueGroupTrafficOverview.vue, src/Report/Legacy/Traffic/QueueTrafficDetail.vue, src/Report/Legacy/Traffic/QueueTrafficOverview.vue, src/Report/Legacy/Traffic/VoicemailDetail.vue, src/Report/Legacy/Traffic/VoicemailOverview.vue
+ update of SLA input component
=> VM reports

src/Monitor/Widget/InqueuesView.vue
=> Queue Statistics are not updated #384

src/Report/Legacy/CDR/CDR.vue
+ removed segment fields from CDR (issue #485)
=> Fields in CDR do not get bigger dynamically ... #587

src/Report/Legacy/Agent/AgentGroupProductivity.vue, src/Report/Legacy/Agent/AgentProductivityByGroup.vue, src/Report/reports.scss
- Agent Productivity reports repaired
=> issue #630

src/Report/Legacy/Agent/AgentActivityByGroup.vue, src/Report/Legacy/Agent/AgentAnswerPerformanceByGroup.vue, src/Report/Legacy/Agent/AgentAvailability.vue, src/Report/Legacy/Agent/AgentGroupProductivity.vue, src/Report/Legacy/Agent/AgentProductivityByGroup.vue, src/Report/Legacy/Agent/AgentStatesOverview.vue, src/Report/Legacy/Agent/UnansweredCallDetails.vue
- adapt reports to latest roles/permissions changes
- agent productivity reports update
=> #628, #629, #655

src/Report/Legacy/Agent/AgentActivityByGroup.vue
- problem caused by existence of stats for removed agents
=> Agent Activity by Group report is not displaying any entries #663

src/Report/Legacy/Agent/AgentAnswerPerformanceByGroup.vue
- update for removed agent case
=> Agent Answer Perf. report
